### ISSUE TITLE
The action does not support tags

### ISSUE THREAD

**Issue by seancorfield** [clj-holmes/clj-holmes-action#10]
Since the clj-holmes-rules correctness check is broken -- see https://github.com/clj-holmes/clj-holmes-rules/issues/41 -- I want to exclude it from GHA by specifying `tags: 'security'` but that is not accepted.

**Comment by samumbach** [comment]
I've been considering potential approaches for adding tags as another GitHub action input. I figured it would be nice to expose all the clj-holmes CLI options as GitHub action inputs for future flexibility and consistency of approach.

It appears standard-ish for GitHub actions to support lists of items within inputs as either comma- or newline-separated lists:

- https://github.com/actions/create-github-app-token/blob/93c1f04d6f14ea5b416e7a8dfd80446101c6adef/action.yml#L18
- https://github.com/actions/reusable-workflows/blob/95d9656793415e47f574f7967f3850ea3bf5a7ed/.github/workflows/update-config-files.yml#L25
- https://github.com/actions/cache/blob/5a3ec84eff668545956fd18022155c47e93e2684/action.yml#L12

Assuming clj-holmes tags/priorities/severities will never contain `,`, a comma-separated list for each seems reasonable and simple (for both the consumer of the GitHub action and for the implementation within `entrypoint.sh`.

For ignored-paths, it's unlikely but _possible_ to want to include commas (and maybe leading and trailing whitespace). I also realized that while the clj-holmes CLI supports supplying multiple `--ignored-paths` options, it's not strictly necessary since you could always use regex alternation `|` to combine all your exclusions into a single pattern. For the ignored-paths input, I'd rather forgo any string manipulation and use the input value exactly as specified.

Usage of the updated GitHub action could look something like this:

```yaml
#...
jobs:
  myjob:
    #...
    steps:
    #...
      - name: Scan
        uses: clj-holmes/clj-holmes-action@main
        with:
          rules-repository: 'git://org/private-rules-repo#main'
          output-type: 'json'
          output-file: 'scan-results.json'
          fail-on-result: 'true'
          ignored-paths: '\.cljs$|test/'
          rule-tags: security,vulnerability,ssl
          rule-severities: error,warning,info
          rule-precisions: low,medium,high,very-high
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```


@mthbernardes @seancorfield Any thoughts on this approach?
